baseline: " A Computer Science major at Allegheny College "
theme:
  - hyde
  - netlify
  - netlify-cms
keywords:
  - Cecil
  - Static Site Generator
  - SSG
author: Arnaud Ligny
date:
  format: j F Y
  timezone: Europe/Paris
hyde:
  sidebar:
    sticky: true
  theme: ""
  reverse: false
title: "Daniel Bekele "
language: en
languages:
  - code: en
    locale: en
  - code: fr
    locale: fr_FR
    config:
      baseline: Votre assistant de blog
      description: Un blog statique prêt à l’emploi, propulsé par Cecil.
description: "A software engineering pursing a career with computer science  "
baseurl: /
canonicalurl: true
